/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.daoNV;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;
import java.io.*;
import model.NhanVien;
import java.sql.*;
//import database.*;


/**
 *
 * @author ADMIN
 */
public class qlnvView extends javax.swing.JFrame {

    /**
     * Creates new form qlnvView
     */
    private ArrayList<NhanVien> list;
    private ArrayList<NhanVien> res;
    private DefaultTableModel model;
    public qlnvView() {
        initComponents();
        this.setLocationRelativeTo(null);
        model=(DefaultTableModel)jTable1.getModel();
        try {
            showTable();
        } catch (IOException ex) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        text3 = new javax.swing.JTextField();
        text4 = new javax.swing.JTextField();
        text5 = new javax.swing.JTextField();
        text6 = new javax.swing.JTextField();
        text7 = new javax.swing.JTextField();
        text10 = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        refesh = new javax.swing.JButton();
        search = new javax.swing.JComboBox<>();
        text8 = new javax.swing.JComboBox<>();
        text9 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        header = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bai tap lon: Quan ly nhan vien");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mã nhân viên");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Họ và tên");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Giới tính");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ngày sinh");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Phòng ban");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Địa chỉ");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Số điện thoại");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Chức vụ");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Lương cơ bản");

        text1.setBackground(new java.awt.Color(255, 255, 255));
        text1.setForeground(new java.awt.Color(0, 0, 0));
        text1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        text2.setBackground(new java.awt.Color(255, 255, 255));
        text2.setForeground(new java.awt.Color(0, 0, 0));
        text2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text3.setBackground(new java.awt.Color(255, 255, 255));
        text3.setForeground(new java.awt.Color(0, 0, 0));
        text3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text4.setBackground(new java.awt.Color(255, 255, 255));
        text4.setForeground(new java.awt.Color(0, 0, 0));
        text4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text5.setBackground(new java.awt.Color(255, 255, 255));
        text5.setForeground(new java.awt.Color(0, 0, 0));
        text5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text6.setBackground(new java.awt.Color(255, 255, 255));
        text6.setForeground(new java.awt.Color(0, 0, 0));
        text6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text7.setBackground(new java.awt.Color(255, 255, 255));
        text7.setForeground(new java.awt.Color(0, 0, 0));
        text7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text10.setBackground(new java.awt.Color(255, 255, 255));
        text10.setForeground(new java.awt.Color(0, 0, 0));
        text10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        add.setBackground(new java.awt.Color(153, 255, 153));
        add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 0));
        add.setText("Thêm");
        add.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(153, 255, 204));
        update.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(0, 0, 0));
        update.setText("Sửa");
        update.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 102, 102));
        delete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("Xóa");
        delete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        refesh.setBackground(new java.awt.Color(204, 204, 204));
        refesh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        refesh.setForeground(new java.awt.Color(0, 0, 0));
        refesh.setText("Refesh");
        refesh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        refesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refeshActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(204, 204, 204));
        search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(0, 0, 0));
        search.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm kiếm theo mã nhân viên", "Tìm kiếm theo tên", "Tìm kiếm theo phòng ban", "Tìm kiếm theo chức vụ" }));
        search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        text8.setBackground(new java.awt.Color(204, 204, 204));
        text8.setForeground(new java.awt.Color(0, 0, 0));
        text8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giam doc", "Ke toan", "Nhan su", "Ki thuat", "San xuat", "Kinh doanh" }));
        text8.setBorder(null);
        text8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text8ActionPerformed(evt);
            }
        });

        text9.setBackground(new java.awt.Color(204, 204, 204));
        text9.setForeground(new java.awt.Color(0, 0, 0));
        text9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giam doc", "Pho giam doc", "Truong phong", "Pho phong", "Nhan vien" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refesh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(text2)
                            .addComponent(text3)
                            .addComponent(text4)
                            .addComponent(text5)
                            .addComponent(text6)
                            .addComponent(text7)
                            .addComponent(text10)
                            .addComponent(text8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(text8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(text9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(text10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refesh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ và tên", "Giới tính", "Ngày sinh", "Số điện thoại", "Email", "Địa chỉ", "Phòng ban", "Chức vụ", "Lương CB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(70);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(1).setMinWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(2).setMinWidth(60);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(3).setMinWidth(80);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(80);
            jTable1.getColumnModel().getColumn(4).setMinWidth(100);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setMinWidth(200);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(6).setMinWidth(150);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(7).setMinWidth(100);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(8).setMinWidth(100);
            jTable1.getColumnModel().getColumn(8).setMaxWidth(100);
        }

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        header.setForeground(new java.awt.Color(0, 0, 0));
        header.setText("QUẢN LÝ NHÂN VIÊN CÔNG TY X");

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 0, 0));
        logout.setText("Đăng xuất");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(507, 507, 507)
                .addComponent(header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text1ActionPerformed




    /*
     * nut sua thong tin nhan vien
     */
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:

        int i=jTable1.getSelectedRow();
        NhanVien nv=new NhanVien();
        String s1= text1.getText();String s2= text2.getText();
        String s3= text3.getText();String s4= text4.getText();
        String s5= text5.getText();String s6= text6.getText();
        String s7= text7.getText();
        String s8= ""; int k=text8.getSelectedIndex();
        if(k==0) s8="Giam doc";
        if(k==1) s8="Ke toan";
        if(k==2) s8="Nhan su";
        if(k==3) s8="Ki thuat";
        if(k==4) s8="San xuat";
        if(k==5) s8="Kinh doanh";
        String s9= (String) text9.getSelectedItem();
        if(!s1.isEmpty()) nv.setId(s1);
        if(!s2.isEmpty()) nv.setName(s2);
        if(!s3.isEmpty()) nv.setGender(s3);
        if(!s4.isEmpty()) nv.setDob(s4);
        if(!s5.isEmpty()) nv.setPhoneNumber(s5);
        if(!s6.isEmpty()) nv.setEmail(s6);
        if(!s7.isEmpty()) nv.setAddress(s7);
        if(!s8.isEmpty()) nv.setDepartment(s8);
        if(!s9.isEmpty()) nv.setPosition(s9);
        try {
            int s10=Integer.valueOf(text10.getText());
            nv.setSalary(s10);
        } catch (Exception e) {}

        int ok=1;
        list=res;
        for (int x=0;x<list.size();x++) {
            if(x==i) continue;
            if(list.get(x).getId().toLowerCase().equals(s1.toLowerCase())) {
                ok=0;break;
            }
        }

        if(ok==1){
            if(JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn sửa không?")==JOptionPane.YES_OPTION){
                try {
                    text1.setText("");text2.setText("");text3.setText("");text4.setText("");text5.setText("");
                    text6.setText("");text7.setText("");text8.setSelectedIndex(0);;text9.setSelectedIndex(0);text10.setText("");
                    new daoNV().deleteNV(list.get(i).getId());
                    JOptionPane.showMessageDialog(this, "Sửa thông tin thành công!");
                    new daoNV().addNV(nv);
                } catch (Exception e) {}
            }
        } else JOptionPane.showMessageDialog(this, "Mã nhân viên không hợp lệ!!");

        // try {
        //     new daoNV().addNV(nv);
        // } catch (Exception e) {}
        try {
            showTable();
        } catch (IOException ex) {}
    }//GEN-LAST:event_updateActionPerformed




    /*
     * nut them nhan vien
     */
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String s1= text1.getText();String s2= text2.getText();
        String s3= text3.getText();String s4= text4.getText();
        String s5= text5.getText();String s6= text6.getText();
        String s7= text7.getText();String s9= (String) text9.getSelectedItem();
        String s8= ""; int k=text8.getSelectedIndex();
        if(k==0) s8="Giam doc";
        if(k==1) s8="Ke toan";
        if(k==2) s8="Nhan su";
        if(k==3) s8="Ki thuat";
        if(k==4) s8="San xuat";
        if(k==5) s8="Kinh doanh";
        int s10=0,ok=1;
        try {
            s10=Integer.valueOf(text10.getText());
        } catch (Exception e) {
            // TODO: handle exception
            ok=0;
        }
        for (NhanVien nhanVien : list) {
            if(nhanVien.getId().equals(s1)){
                ok=0;break;
            }
        }
        
        if(s1.isEmpty()||s2.isEmpty()||s3.isEmpty()||s4.isEmpty()||s5.isEmpty()||s6.isEmpty()||s7.isEmpty()||s8.isEmpty()||s9.isEmpty()) ok=0;

        if(ok==1){
            NhanVien nv=new NhanVien(s1, s2, s3, s4, s5, s6, s7, s8, s9, s10);
            try {
                daoNV daonv=new daoNV();
                daonv.addNV(nv);
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                text1.setText("");text2.setText("");text3.setText("");text4.setText("");text5.setText("");
                text6.setText("");text7.setText("");text8.setSelectedIndex(0);;text9.setSelectedIndex(0);;text10.setText("");
            } catch (Exception ex) {}
            
            try {
                showTable();
            } catch (IOException ex) {}
            System.out.println(list.size());
        } else JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ, xin mời nhập lại.");
    }//GEN-LAST:event_addActionPerformed



    /*
     * nut xoa nhan vien
     */
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        list=res;
        NhanVien nhanVien=list.get(i);
        // ArrayList<NhanVien> tmp=new ArrayList<>();
        // for (NhanVien nv : list) {
        //     if(!nv.getId().equals(nhanVien.getId())) tmp.add(nv);
        // }

        int res=JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?");
        if(res==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            try {
                new daoNV().deleteNV(nhanVien.getId());
            } catch (Exception e) {}
        }
        
        try {
            showTable();
        } catch (IOException ex) {}
        System.out.println(list.size());
    }//GEN-LAST:event_deleteActionPerformed



    /*
     * nut refresh
     */
    private void refeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeshActionPerformed
        // TODO add your handling code here:
        text1.setText("");text2.setText("");text3.setText("");text4.setText("");text5.setText("");
        text6.setText("");text7.setText("");text8.setSelectedIndex(0);;text9.setSelectedIndex(0);;text10.setText("");
        jTable1.setAutoCreateRowSorter(false);
        try {
            showTable();
        } catch (IOException e) {}
    }//GEN-LAST:event_refeshActionPerformed



    /*
     * nut tim kiem
     */
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        ArrayList<NhanVien> tmp=new daoNV().getlistNV();
        res=new ArrayList<>();
        model=(DefaultTableModel)jTable1.getModel();
        int x=search.getSelectedIndex();
        if(x==0){
            String s=text1.getText();
            model.setRowCount(0);
            for (NhanVien nhanVien : tmp) {
                if(nhanVien.getId().toLowerCase().contains(s.toLowerCase())){
                    model.addRow(new Object[]{
                        nhanVien.getId(),nhanVien.getName(),nhanVien.getGender(),nhanVien.getDob(),nhanVien.getPhoneNumber(),
                        nhanVien.getEmail(),nhanVien.getAddress(),nhanVien.getDepartment(),nhanVien.getPosition(),nhanVien.getSalary()
                    });
                    res.add(nhanVien);
                }
            }
            
        } else if(x==1){
            String s=text2.getText();
            model.setRowCount(0);
            for (NhanVien nhanVien : tmp) {
                if(nhanVien.getName().toLowerCase().contains(s.toLowerCase())){
                    model.addRow(new Object[]{
                        nhanVien.getId(),nhanVien.getName(),nhanVien.getGender(),nhanVien.getDob(),nhanVien.getPhoneNumber(),
                        nhanVien.getEmail(),nhanVien.getAddress(),nhanVien.getDepartment(),nhanVien.getPosition(),nhanVien.getSalary()
                    });
                    res.add(nhanVien);
                }
            }
        } else if(x==2){
            String s= ""; int k=text8.getSelectedIndex();
            if(k==0) s="Giam doc";
            if(k==1) s="Ke toan";
            if(k==2) s="Nhan su";
            if(k==3) s="Ki thuat";
            if(k==4) s="San xuat";
            if(k==5) s="Kinh doanh";
            model.setRowCount(0);
            for (NhanVien nhanVien : tmp) {
                if(nhanVien.getDepartment().toLowerCase().equals(s.toLowerCase())){
                    model.addRow(new Object[]{
                        nhanVien.getId(),nhanVien.getName(),nhanVien.getGender(),nhanVien.getDob(),nhanVien.getPhoneNumber(),
                        nhanVien.getEmail(),nhanVien.getAddress(),nhanVien.getDepartment(),nhanVien.getPosition(),nhanVien.getSalary()
                    });
                    res.add(nhanVien);
                }
            }
        } else if(x==3){
            String s=(String)text9.getSelectedItem();
            model.setRowCount(0);
            for (NhanVien nhanVien : tmp) {
                if(nhanVien.getPosition().toLowerCase().equals(s.toLowerCase())){
                    model.addRow(new Object[]{
                        nhanVien.getId(),nhanVien.getName(),nhanVien.getGender(),nhanVien.getDob(),nhanVien.getPhoneNumber(),
                        nhanVien.getEmail(),nhanVien.getAddress(),nhanVien.getDepartment(),nhanVien.getPosition(),nhanVien.getSalary()
                    });
                    res.add(nhanVien);
                }
            }
        }
        System.out.println(res.size());
    }//GEN-LAST:event_searchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        NhanVien nv=res.get(i);
        text1.setText(nv.getId());text2.setText(nv.getName());text3.setText(nv.getGender());text4.setText(nv.getDob());text5.setText(nv.getPhoneNumber());
        text6.setText(nv.getEmail());text7.setText(nv.getAddress());text8.setSelectedItem(nv.getDepartment());text9.setSelectedItem(nv.getPosition());text10.setText(nv.getSalary()+"");

    }//GEN-LAST:event_jTable1MouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed


    /*
     * nut dang xuat
     */
    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không??")==JOptionPane.YES_OPTION){
            this.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    LoginView login=new LoginView("Login");
                }
            });
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void text8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        Connection c=JDBCUtil.getConnection();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qlnvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qlnvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qlnvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qlnvView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        </editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qlnvView().setVisible(true);
                try {
                    new qlnvView().showTable();
                } catch (Exception e) {
                    // TODO: handle exception
                }
            }
        });
    }
    
    /*
     * ham hien thi bang
     */
    private void showTable() throws IOException {
        list=new daoNV().getlistNV();
        res=new daoNV().getlistNV();
        model.setRowCount(0);
        for (NhanVien nhanVien : list) {
            model.addRow(new Object[]{
                nhanVien.getId(),nhanVien.getName(),nhanVien.getGender(),nhanVien.getDob(),nhanVien.getPhoneNumber(),
                nhanVien.getEmail(),nhanVien.getAddress(),nhanVien.getDepartment(),nhanVien.getPosition(),nhanVien.getSalary()
            });
        }
        jTable1.setAutoCreateRowSorter(true);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton delete;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout;
    private javax.swing.JButton refesh;
    private javax.swing.JComboBox<String> search;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text10;
    private javax.swing.JTextField text2;
    private javax.swing.JTextField text3;
    private javax.swing.JTextField text4;
    private javax.swing.JTextField text5;
    private javax.swing.JTextField text6;
    private javax.swing.JTextField text7;
    private javax.swing.JComboBox<String> text8;
    private javax.swing.JComboBox<String> text9;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
